package com.bw.mmcro.traces.mapper;

import com.bw.mmcro.traces.domain.TraceUserCrops;
import com.bw.mmcro.traces.domain.vo.CropsVo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TraceUserCropsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace_user_crops
     *
     * @mbg.generated Wed Oct 28 00:08:24 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace_user_crops
     *
     * @mbg.generated Wed Oct 28 00:08:24 CST 2020
     */
    int insert(TraceUserCrops record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace_user_crops
     *
     * @mbg.generated Wed Oct 28 00:08:24 CST 2020
     */
    int insertSelective(TraceUserCrops record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace_user_crops
     *
     * @mbg.generated Wed Oct 28 00:08:24 CST 2020
     */
    TraceUserCrops selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace_user_crops
     *
     * @mbg.generated Wed Oct 28 00:08:24 CST 2020
     */
    int updateByPrimaryKeySelective(TraceUserCrops record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace_user_crops
     *
     * @mbg.generated Wed Oct 28 00:08:24 CST 2020
     */
    int updateByPrimaryKey(TraceUserCrops record);

    List<TraceUserCrops> getCropsByUsername(String username);

    int updateByCropsId(String cropsId);

    int updateMachingStatus(CropsVo cropsVo);

    int updateProductWriteStatus(String cropsId);

    int productOutFactory(String cropsId);
}
