package com.bw.mmcro.traces.mapper;

import com.bw.mmcro.traces.domain.TraceTransport;
import com.bw.mmcro.traces.domain.vo.CropsVo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TraceTransportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace_transport
     *
     * @mbg.generated Tue Nov 03 22:03:31 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace_transport
     *
     * @mbg.generated Tue Nov 03 22:03:31 CST 2020
     */
    int insert(TraceTransport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace_transport
     *
     * @mbg.generated Tue Nov 03 22:03:31 CST 2020
     */
    int insertSelective(TraceTransport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace_transport
     *
     * @mbg.generated Tue Nov 03 22:03:31 CST 2020
     */
    TraceTransport selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace_transport
     *
     * @mbg.generated Tue Nov 03 22:03:31 CST 2020
     */
    int updateByPrimaryKeySelective(TraceTransport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace_transport
     *
     * @mbg.generated Tue Nov 03 22:03:31 CST 2020
     */
    int updateByPrimaryKey(TraceTransport record);

    List<TraceTransport> listTransport(String driverId);

    int updateByCropsId(TraceTransport traceTransport);

    List<TraceTransport> listCrops(String deptId);

    int changeInToOut(String cropsId);

    List<CropsVo> queryCropsList(Integer deptId);

    int updateReceiveStatus(TraceTransport traceTransport);
}
